version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: personal-proj-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - personal-proj-volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always

volumes:
  personal-proj-volume:
    driver: local
