version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: personal-proj-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - personal-proj-volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticvolume:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - postgres

  logstash:
    container_name: logstash
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
      - postgres
    restart: on-failure

volumes:
  personal-proj-volume:
    driver: local
  elasticvolume:

